<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Metro Cuadrado Test" duration-ms="53624" started-at="2020-03-08T18:52:20Z" finished-at="2020-03-08T18:53:14Z">
    <groups>
    </groups>
    <test name="Calcular Credito Hipotecario Metro Cuadrado" duration-ms="53624" started-at="2020-03-08T18:52:20Z" finished-at="2020-03-08T18:53:14Z">
      <class name="com.tyba.metrocuadrado.test.TestCalcularCreditoHipotecario">
        <test-method status="PASS" signature="test()[pri:0, instance:com.tyba.metrocuadrado.test.TestCalcularCreditoHipotecario@668bc3d5]" name="test" is-config="true" duration-ms="48" started-at="2020-03-08T13:52:20Z" finished-at="2020-03-08T13:52:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.tyba.metrocuadrado.test.TestCalcularCreditoHipotecario@668bc3d5]" name="setUp" is-config="true" duration-ms="31185" started-at="2020-03-08T13:52:20Z" finished-at="2020-03-08T13:52:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="calcularCreditoVivienda(java.lang.reflect.Method)[pri:0, instance:com.tyba.metrocuadrado.test.TestCalcularCreditoHipotecario@668bc3d5]" name="calcularCreditoVivienda" duration-ms="18104" started-at="2020-03-08T13:52:52Z" description="Calcular Credito Hipotecario Vivienda" finished-at="2020-03-08T13:53:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.tyba.metrocuadrado.test.TestCalcularCreditoHipotecario.calcularCreditoVivienda(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- calcularCreditoVivienda -->
        <test-method status="SKIP" signature="verificareEstimacionCredito(java.lang.reflect.Method)[pri:1, instance:com.tyba.metrocuadrado.test.TestCalcularCreditoHipotecario@668bc3d5]" name="verificareEstimacionCredito" duration-ms="476" started-at="2020-03-08T13:53:11Z" description="Verificar Estimacion Credito" finished-at="2020-03-08T13:53:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.tyba.metrocuadrado.test.TestCalcularCreditoHipotecario.verificareEstimacionCredito(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [2500000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [2500000]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.tyba.metrocuadrado.test.TestCalcularCreditoHipotecario.verificareEstimacionCredito(TestCalcularCreditoHipotecario.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verificareEstimacionCredito -->
        <test-method status="FAIL" signature="verificareEstimacionCredito(java.lang.reflect.Method)[pri:1, instance:com.tyba.metrocuadrado.test.TestCalcularCreditoHipotecario@668bc3d5]" name="verificareEstimacionCredito" duration-ms="373" started-at="2020-03-08T13:53:12Z" description="Verificar Estimacion Credito" finished-at="2020-03-08T13:53:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.tyba.metrocuadrado.test.TestCalcularCreditoHipotecario.verificareEstimacionCredito(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [2500000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [2500000]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.tyba.metrocuadrado.test.TestCalcularCreditoHipotecario.verificareEstimacionCredito(TestCalcularCreditoHipotecario.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verificareEstimacionCredito -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.tyba.metrocuadrado.test.TestCalcularCreditoHipotecario@668bc3d5]" name="tearDown" is-config="true" duration-ms="1278" started-at="2020-03-08T13:53:13Z" finished-at="2020-03-08T13:53:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tyba.metrocuadrado.test.TestCalcularCreditoHipotecario -->
    </test> <!-- Calcular Credito Hipotecario Metro Cuadrado -->
  </suite> <!-- Metro Cuadrado Test -->
</testng-results>
